# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd1b4e959c07cd0875c101b7e0dc4b48f6ea361875fa8e6f554fd08a1a5976c645291107fbdb2df45ff519884d0a83f23bdd9aeba78d1bf69dd5aed685bcd199

test:
  secret_key_base: 6f5171b6c5e2db0693e0e210a2175bb6d17a6bf1f5b22d7fa07bd7e450c185d1f67caada0d5775f4347d3fb9ac9c8aae923c70a427fc1eb5fcbf82e382071adf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
